In [1]:
import sys
from pathlib import Path

project_root = Path(
    r"C:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\GlobalPPREstimation"
)
module_dir = str(project_root / "tools" / "scientific_code" / "PPREstimation")

if module_dir not in sys.path:
    sys.path.insert(0, module_dir)

import pandas as pd
import numpy as np
from PPRCalculator import PPRCalculator
from ModelData import ModelData

# Loading

In [2]:
model_path = (
    "model.json"
)

model = ModelData(
    model_path,
    model_name="name",
    model_year="year",
)

# Inspect or edit these before constructing the calculator:
# model.groups_data['biomass_accum'] = np.nan
# model.groups_data
# model.DC
# model.det_fate

In [3]:
calculator = PPRCalculator.from_modeldata(
    modeldata=model,
    underdetermined=True,     # Estimate missing flows using LIM if True
    zero_catch=True,           # Replace missing catch with zero
    zero_biomass_accum=False,   # Replace missing biomass accumulation with zero
    default_gs=True,           # Supply GS=0.2 for regular groups missing GS
    weight_flow=1.0,           # LIM minimum-flow penalty weight
    weight_guess=1.0,          # LIM guess-deviation penalty weight
    normalize_DC=True,         # Normalize consumer diet sums if True
    DC_tol=0.001,             # Allowed deviation of diet sums from 1
    balance_BA_after_DC_normalization=False
)

C:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\GlobalPPREstimation\tools\scientific_code\PPREstimation\ModelData.py:663: RuntimeWarning: 4 consumer group(s) have a diet composition (including diet_import) that does not sum to 1 (tol=0.001): 34 (Green sea turtle)=1.0020, 20 (Large hake )=1.0090, 16 (Chub mackerel)=0.9952, 7 (Chrysaora plocamia)=1.0450.
  warnings.warn(f"{len(bad)} consumer group(s) have a diet composition (including diet_import) "

In [13]:
# calculator.get_det_fate().rename(index=calculator.seq2name, columns=calculator.seq2name)

# DC

In [12]:
model.DC.sum(axis=1).rename(index=model.seq2name).round(decimals=7)
# model.DC.rename(index=model.seq2name, columns=model.seq2name).round(decimals=7).columns
# model.DC.rename(index=model.seq2name, columns=model.seq2name).round(decimals=7)

diet_import                 0.0
Detritus                    0.0
Marine mammals              1.0
Sharks                      1.0
Small yellow croakers       1.0
Large yellow croakers       1.0
Omnivores                   1.0
Benthivores/piscivores      1.0
Planktivores/piscivores     1.0
Planktivores/Benthivores    1.0
Bombay duck                 1.0
Hairtails                   1.0
Piscivores                  1.0
Benthivores                 1.0
Planktivores                1.0
Cephalopods                 1.0
Shrimps                     1.0
Crabs                       1.0
Other invertebrates         1.0
Echinoderms                 1.0
Benthic Crustaceans         1.0
Mollusks                    1.0
Polychaetes                 1.0
Zooplankton                 1.0
Phytoplankton               0.0
dtype: float64

In [7]:
calculator.get_DC().sum(axis=1).round(decimals=3)

39    0.0
38    0.0
37    1.0
36    1.0
35    1.0
34    1.0
33    1.0
32    1.0
31    1.0
30    1.0
29    1.0
28    1.0
27    1.0
26    1.0
25    1.0
24    1.0
23    1.0
22    1.0
21    1.0
20    1.0
19    1.0
18    1.0
17    1.0
16    1.0
15    1.0
14    1.0
13    1.0
12    1.0
11    1.0
10    1.0
9     1.0
8     1.0
7     1.0
6     1.0
5     1.0
4     1.0
3     1.0
2     0.0
1     0.0
dtype: float64

# Groups Data

In [4]:
model.groups_data.round(decimals=7)[['group_name', 'biomass', 'biomass_accum']]

                         group_name    biomass  biomass_accum
group_seq
39                 Benthic detritus  60.000000            NaN
38                 Pelagic detritus  20.000000            NaN
37                    Fishery offal   0.050000            NaN
36                     Anchovy eggs   0.436000            NaN
35               Leatherback turtle   0.000162            NaN
34                 Green sea turtle   0.000343            NaN
33                        Cetaceans   0.064500            NaN
32                        Pinnipeds   0.062500            NaN
31                         Seabirds   0.038500            NaN
30                  Chondrichthyans   0.052500            NaN
29                          Catfish   0.613500            NaN
28                        Sea robin   0.554000            NaN
27                 Medium sciaenids   0.293500            NaN
26             Medium demersal fish   0.205500            NaN
25                           Conger   0.011500            NaN
24                    Butter fishes   0.019000            NaN
23            Benthic elasmobranchs   0.061500            NaN
22              Small demersal fish   5.230000            NaN
21                         Flatfish   0.025000            NaN
20                      Large hake    0.041500            NaN
19                      Medium hake   0.288500            NaN
18                      Small hake    2.008000            NaN
17         Other large pelagic fish   1.173000            NaN
16                    Chub mackerel   7.690000            NaN
15                   Horse mackerel   7.299000            NaN
14         Other small pelagic fish  10.995006            NaN
13                Other cephalopods   1.806318            NaN
12                      Jumbo squid   0.383500            NaN
11                 Mesopelagic fish  14.628500            NaN
10                         Anchovy   58.316502            NaN
9                           Sardine  10.738000            NaN
8                      Macrobenthos  23.167000            NaN
7                Chrysaora plocamia   8.464286            NaN
6            Gelatinous zooplankton   0.009068            NaN
5                  Macrozooplankton  37.424713            NaN
4                   Mesozooplankton  24.082001            NaN
3                  Microzooplankton  13.542136            NaN
2            Dino/silicoflagellates  13.377000            NaN
1                           Diatoms  34.088501            NaN
40                      diet_import        NaN            NaN

In [31]:
calculator.get_groups_df().round(decimals=7)[['group_name', 'biomass', 'biomass_accum']]

                          group_name  biomass  biomass_accum
group_seq
30                       diet_import    1.000       0.000000
29                          Detritus    1.000   21997.696125
28                     Phytoplankton  160.943       9.120485
27                      Phytobenthos   12.579       0.042541
26           Herbivorous zooplankton  197.480      17.429786
25             Predatory zooplankton   86.792     -15.461188
24                 2nd level benthos  143.052       0.288498
23         Carnivorous invertebrates   12.948       0.159808
22                         Jellyfish    0.980       0.003562
21                            Squids    1.541       0.142199
20                 Crabs and shrimps    2.599      -1.255300
19          Other mesopelagic fishes    1.578      -0.687714
18                      Bathylagidae   14.698       0.028512
17                       Myctophidae    1.491      -0.003368
16                       Ammodytidae    0.314       0.010905
15               Other bottom fishes    0.515      -0.151733
14                          Cottidae    0.212      -0.056233
13                    Pleuronectidae    1.186      -0.011601
12                     Other Gadidae    0.306       0.028530
11                   Pacific Sardine    0.667       0.011717
10                           Capelin    2.580       0.077379
9                             Salmon    0.147       0.030209
8                    Pacific herring    0.818       0.047337
7                       Juv. pollock    2.119       0.047882
6                    Walleye pollock    2.475       0.621150
5                           Seabirds    0.005       0.000000
4                          Pinnipeds    0.053       0.001002
3                       Sperm whales    0.011       0.000000
2                     Toothed whales    0.010       0.000000
1                      Baleen whales    0.958       0.006993

In [26]:
# model.groups_data.round(decimals=7)[['group_name', 'ge', 'ee']]

In [27]:
# calculator.get_groups_df().round(decimals=7)[['group_name', 'ge', 'ee', 'tl']]

# Is Model Balanced

In [4]:
balanced, p, q = calculator.is_model_balanced()
balanced

True

In [22]:
(100 * (p - calculator.p)/p).rename(index=calculator.seq2name)

group_seq
diet_import                          NaN
Detritus                    0.000000e+00
Marine mammals              0.000000e+00
Sharks                      0.000000e+00
Small yellow croakers       0.000000e+00
Large yellow croakers       0.000000e+00
Omnivores                  -1.542532e-14
Benthivores/piscivores      0.000000e+00
Planktivores/piscivores     0.000000e+00
Planktivores/Benthivores    0.000000e+00
Bombay duck                 0.000000e+00
Hairtails                   0.000000e+00
Piscivores                  0.000000e+00
Benthivores                 0.000000e+00
Planktivores                0.000000e+00
Cephalopods                 0.000000e+00
Shrimps                     0.000000e+00
Crabs                       0.000000e+00
Other invertebrates         0.000000e+00
Echinoderms                 0.000000e+00
Benthic Crustaceans         0.000000e+00
Mollusks                    0.000000e+00
Polychaetes                 0.000000e+00
Zooplankton                 0.000000e+00
Phytoplankton               0.000000e+00
dtype: float64

In [8]:
calc_balanced = calculator.balanced_model
print(calc_balanced.n_balance_runs)
balanced, p, q = calc_balanced.is_model_balanced()
100 * (p - calc_balanced.p)/p

1

group_seq
25             NaN
24    0.000000e+00
23    0.000000e+00
22    0.000000e+00
21    0.000000e+00
20    0.000000e+00
19    0.000000e+00
18    0.000000e+00
17    0.000000e+00
16    0.000000e+00
15    0.000000e+00
14   -1.731950e-14
13    0.000000e+00
12    0.000000e+00
11    0.000000e+00
10    0.000000e+00
9    -2.107821e-14
8     0.000000e+00
7     0.000000e+00
6     0.000000e+00
5     0.000000e+00
4    -2.132190e-14
3     0.000000e+00
2     0.000000e+00
1     0.000000e+00
dtype: float64

# Diagnostics

In [25]:
result, sppr, A, L = calculator.diagnose_sppr(
    TE_option='GE',
    return_sppr=True,
    det_collapse_mode='auto',
)

In [20]:
result, sppr, A, L = calculator.diagnose_sppr(
    TE_option='TE',
    return_sppr=True,
    det_collapse_mode='auto',
)

C:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\GlobalPPREstimation\tools\scientific_code\PPREstimation\PPRCalculator.py:2715: RuntimeWarning: 5 group(s) have TE=0 because EE=0 (M0=p): 35 (Leatherback turtle), 34 (Green sea turtle), 33 (Cetaceans), 32 (Pinnipeds), 31 (Seabirds). Their consumed PP is dropped, so the TE SPPR will not balance (multi-DET: re-credit not applied).
  warnings.warn(
C:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\GlobalPPREstimation\tools\scientific_code\PPREstimation\PPRCalculator.py:2731: RuntimeWarning: 1 group(s) have near-zero TE (0 < EE << 1): 7 (Chrysaora plocamia). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(

In [22]:
sppr.rename(index=calculator.seq2name, columns=calculator.seq2name).sum(axis=1)
# sppr.rename(index=calculator.seq2name, columns=calculator.seq2name)

diet_import                      1.000000
Benthic detritus                 0.000000
Pelagic detritus                 0.304285
Fishery offal                    0.000000
Anchovy eggs                     0.000000
Dino/silicoflagellates           1.000000
Diatoms                          1.000000
Leatherback turtle               0.000000
Green sea turtle                 0.000000
Cetaceans                        0.000000
Pinnipeds                        0.000000
Seabirds                         0.000000
Chondrichthyans               7596.014295
Catfish                         74.481961
Sea robin                      110.637070
Medium sciaenids              4951.016719
Medium demersal fish            85.358492
Conger                      447352.649724
Butter fishes               319786.504476
Benthic elasmobranchs         7955.355087
Small demersal fish             27.460928
Flatfish                       354.754813
Large hake                   47006.292296
Medium hake                   3236.292638
Small hake                     731.770146
Other large pelagic fish      1280.174581
Chub mackerel                 1951.049028
Horse mackerel                 799.915344
Other small pelagic fish        47.380070
Other cephalopods               13.826862
Jumbo squid                    831.745041
Mesopelagic fish               225.086655
Anchovy                         43.673175
Sardine                         48.153928
Macrobenthos                     2.899495
Chrysaora plocamia          381475.864896
Gelatinous zooplankton          30.433622
Macrozooplankton                 5.925465
Mesozooplankton                  6.021856
Microzooplankton                 6.231874
dtype: float64

In [18]:
result['model_input']

{'status': 'WARN',
 'is_model_balanced': True,
 'p_max_rel_residual': 5.0280357151667344e-14,
 'q_max_rel_residual': 1.0088827775208698e-14,
 'dc_rows_sum_to_1': True,
 'dc_max_deviation': 2.220446049250313e-16,
 'n_negative_catch': 0,
 'n_zero_catch': 22,
 'total_catch': 35.5395489180725,
 'has_catch': True,
 'has_ee_issues': True,
 'n_ee0': 5,
 'n_ee_marginal': 1,
 'n_ee_gt_1': 0,
 'ee0_groups': [35, 34, 33, 32, 31],
 'ee_marginal_groups': [7]}

In [19]:
result['divergence']

{'status': 'WARN',
 'solve_error': None,
 'b': 0.0,
 'b_converges': True,
 'rho_living': 0.7316477059387119,
 'living_converges': True,
 'sppr_det': {36: 0.0, 37: 0.0, 38: 0.30428520886027294, 39: 0.0},
 'max_sppr_det': 0.30428520886027294,
 'max_sppr_group': {'seq': 25,
  'tl': 4.1173056366305385,
  'sppr': 447352.6497241629,
  'inv_te': 590.4578556431102},
 'max_tl_group': {'seq': 30,
  'tl': 4.447238103051863,
  'sppr': 7596.014295076642,
  'inv_te': 11.815484985703286},
 'n_negative_sources': 0,
 'expect_negatives': False,
 'near_singular_te': [7]}

In [26]:
if result["divergence"]["solve_error"] is not None:
    print("Requested calculation failed:", result["divergence"]["solve_error"])
else:
    info = calculator.detritus_resolution_info
    method = result["config"]["method"]

    b = (
        info["collapse_b"]
        if method == "pooled_detritus_scaling"
        else info["rho_B"]
    )

    print(f"Method: {method}")
    print(f"b: {b}")
    print(f"Converges: {b < 1}")

Method: pooled_detritus_scaling
b: 0.7659311653485881
Converges: True

In [27]:
result['balance']

{'status': 'OK',
 'is_balanced': True,
 'inflow': 11310.477371346196,
 'outflow': 11310.477371346213,
 'rel_gap': 1.447410581748435e-15}

In [20]:
result['footprint']

{'ppr_all': 0.0,
 'ppr_inner': 0.0,
 'ppr_pp_only': 0.0,
 'npp': 26654.193900000002,
 'ppr2npp': 0.0,
 'ppr2npp_pp_only': 0.0}

In [15]:
result['config']

{'TE_option': 'GE',
 'det_open_mode': 'none',
 'det_theta': 1.0,
 'det_external_sppr': 0.0,
 'det_collapse_mode': 'auto',
 'explicit_TE': False,
 'method': 'pooled_detritus_scaling',
 'would_pool': True,
 'model': 'name (year)'}

In [14]:
result['warnings']

['total catch is 0: every footprint number is identically 0 (the divergence diagnostics are unaffected)',
 "2 group(s) with EE=0 (all production is non-predatory death): 5 (Seabirds), 3 (Sperm whales). Under TE_option='TE' their TE row is 0, which severs them from the nullspace and leaks the PP they consumed",
 'rho(A_LL)=0.8672 is within 0.3 of divergence (max SPPR 2.08e+06 at group 2 (Toothed whales), TL 4.45)']

In [6]:
(sppr<0).any().any()

np.True_