In [1]:
import sys
from pathlib import Path

project_root = Path(
    r"C:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\GlobalPPREstimation"
)
module_dir = str(project_root / "tools" / "scientific_code" / "PPREstimation")

if module_dir not in sys.path:
    sys.path.insert(0, module_dir)

import pandas as pd
from PPRCalculator import PPRCalculator
from ModelData import ModelData

# Loading

In [2]:
model_path = (
    "../models/"
    "36_1_South_China_Sea_SCS-2007_Northern_South_China_Sea_(2000s)/"
    "model.json"
)

model = ModelData(
    model_path,
    model_name="Northern South China Sea",
    model_year="2000s",
)

# Inspect or edit these before constructing the calculator:
# model.groups_data
# model.DC
# model.det_fate

In [3]:
calculator = PPRCalculator.from_modeldata(
    modeldata=model,
    underdetermined=True,     # Estimate missing flows using LIM if True
    zero_catch=True,           # Replace missing catch with zero
    zero_biomass_accum=False,   # Replace missing biomass accumulation with zero
    default_gs=True,           # Supply GS=0.2 for regular groups missing GS
    weight_flow=1.0,           # LIM minimum-flow penalty weight
    weight_guess=1.0,          # LIM guess-deviation penalty weight
    normalize_DC=True,         # Normalize consumer diet sums if True
    DC_tol=0.001,             # Allowed deviation of diet sums from 1
)

C:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\GlobalPPREstimation\tools\scientific_code\PPREstimation\ModelData.py:663: RuntimeWarning: 2 consumer group(s) have a diet composition (including diet_import) that does not sum to 1 (tol=0.001): 33 (Pelagic sharks and rays)=1.0011, 20 (Adult groupers)=0.9990.
  warnings.warn(f"{len(bad)} consumer group(s) have a diet composition (including diet_import) "

# DC

In [ ]:
# model.DC.sum(axis=1).rename(index=model.seq2name).round(decimals=7)
# model.DC.rename(index=model.seq2name, columns=model.seq2name).round(decimals=7).columns
model.DC.rename(index=model.seq2name, columns=model.seq2name).round(decimals=7).loc['Pelagic sharks and rays']

diet_import                         0.0000
Detritus                            0.0000
Marine turtles                      0.0001
Other mammals                       0.0001
Pinnipeds                           0.0001
Seabirds                            0.0001
Pelagic sharks and rays             0.0090
Demersal sharks and rays            0.0001
Pelagic fish (> 30 cm)              0.0050
Juvenile large pelagic fish         0.0250
Pelagic fish (≤ 30 cm)              0.4320
Melon seed                          0.0260
Benthopelagic fish                  0.1790
Adult demersal fish (> 30 cm)       0.0000
Juvenile demersal fish (> 30 cm)    0.0000
Demesral fish (≤ 30 cm)             0.0000
Croakers (> 30 cm)                  0.0000
Juvenile large croakers             0.0000
Croakers (≤ 30 cm)                  0.0130
Adult groupers                      0.0000
Snappers                            0.0000
Pomfret (stromateids)               0.0660
Adult hairtail (trichiurids)        0.0010
Juvenile Hairtail (trichiurids)     0.0010
Lizard fish (synodontids)           0.0000
Bigeyes (priacanthids)              0.0000
Threadfin bream (nemipterids)       0.0000
Cephalopods                         0.2420
Crabs                               0.0010
Shrimps                             0.0000
Sessile/other invertebrates         0.0000
Non-ceph molluscs                   0.0006
Benthic crustaceans                 0.0000
Echinoderms                         0.0000
Polychaetes                         0.0000
Jellyfish                           0.0000
Zooplankton                         0.0000
Benthic producer                    0.0000
Phytoplankton                       0.0000
Name: Pelagic sharks and rays, dtype: float64

In [ ]:
calculator.get_DC().sum(axis=1).round(decimals=3)

39    0.0
38    0.0
37    1.0
36    1.0
35    1.0
34    1.0
33    1.0
32    1.0
31    1.0
30    1.0
29    1.0
28    1.0
27    1.0
26    1.0
25    1.0
24    1.0
23    1.0
22    1.0
21    1.0
20    1.0
19    1.0
18    1.0
17    1.0
16    1.0
15    1.0
14    1.0
13    1.0
12    1.0
11    1.0
10    1.0
9     1.0
8     1.0
7     1.0
6     1.0
5     1.0
4     1.0
3     1.0
2     0.0
1     0.0
dtype: float64

# Groups Data

In [ ]:
model.groups_data.rename(index=model.seq2name, columns=model.seq2name).round(decimals=7)

,group_name,trophic_info,taxon_descr,tl,ge,ee,catch,biomass,pb,qb,...,M0,gs,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import
group_seq,,,,,,,,,,,,,,,,,,,,,
Detritus,Detritus,DET,Non-living detritus.,NaN,NaN,0.005,0.0000,100.0000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Marine turtles,Marine turtles,Regular,Marine turtles; no species list documented.,NaN,NaN,0.300,0.0000,0.0002,0.100,3.500,...,0.000014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Other mammals,Other mammals,Regular,Other marine mammals; no species list documented.,NaN,NaN,0.034,0.0000,0.0158,0.112,10.523,...,0.001709,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Pinnipeds,Pinnipeds,Regular,Pinnipeds; no species list documented.,NaN,NaN,0.290,0.0000,0.0046,0.045,14.768,...,0.000147,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Seabirds,Seabirds,Regular,Seabirds; no species list documented.,NaN,NaN,0.046,0.0000,0.0022,0.060,67.759,...,0.000126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Pelagic sharks and rays,Pelagic sharks and rays,Regular,Pelagic elasmobranchs. No species list documen...,NaN,0.2,0.950,0.0007,0.0011,0.680,3.400,...,0.000037,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Demersal sharks and rays,Demersal sharks and rays,Regular,Demersal elasmobranchs. No species list docume...,NaN,0.2,0.867,0.0010,0.0010,1.200,6.000,...,0.000160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Pelagic fish (> 30 cm),Pelagic fish (> 30 cm),Regular,"Pelagic fish with maximum total length >30 cm,...",NaN,NaN,0.759,0.0821,0.0790,1.400,6.270,...,0.026655,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Juvenile large pelagic fish,Juvenile large pelagic fish,Regular,"Pelagic fish with maximum total length >30 cm,...",NaN,NaN,0.622,0.7384,0.2890,4.260,16.120,...,0.465371,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Pelagic fish (≤ 30 cm),Pelagic fish (≤ 30 cm),Regular,Pelagic fish with maximum total length <=30 cm...,NaN,NaN,0.740,2.3450,1.7720,4.260,17.040,...,1.962667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Melon seed,Melon seed,Regular,Psenopsis anomala; definition: Psenopsis anomala.,NaN,NaN,0.994,0.0499,0.0700,2.410,24.000,...,0.001012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Benthopelagic fish,Benthopelagic fish,Regular,Final table has one Benthopelagic fish group. ...,NaN,0.2,0.479,0.6025,0.9220,3.080,15.420,...,1.479515,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Adult demersal fish (> 30 cm),Adult demersal fish (> 30 cm),Regular,Demersal fish with maximum total length >30 cm...,NaN,NaN,0.747,0.0352,0.0210,2.100,6.207,...,0.011157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Juvenile demersal fish (> 30 cm),Juvenile demersal fish (> 30 cm),Regular,Demersal fish with maximum total length >30 cm...,NaN,NaN,0.722,0.3165,0.1430,3.500,16.144,...,0.139139,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Demesral fish (≤ 30 cm),Demesral fish (≤ 30 cm),Regular,Demersal fish with maximum total length <=30 c...,NaN,NaN,0.950,0.1788,0.3160,4.700,23.500,...,0.074260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Croakers (> 30 cm),Croakers (> 30 cm),Regular,Larimichthys crocea; definition: Large Sciaeni...,NaN,NaN,0.587,0.0080,0.0094,1.430,6.232,...,0.005552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Juvenile large croakers,Juvenile large croakers,Regular,Larimichthys crocea; definition: Large Sciaeni...,NaN,NaN,0.564,0.0710,0.0400,3.300,16.366,...,0.057552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Croakers (≤ 30 cm),Croakers (≤ 30 cm),Regular,Agyrosomus spp.; Pennahia spp.; Pennahia (Agyr...,NaN,NaN,0.958,0.0351,0.0700,3.300,11.276,...,0.009702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Adult groupers,Adult groupers,Regular,Family Serranidae; the final table calls this ...,NaN,NaN,0.950,0.0089,0.0064,1.750,6.100,...,0.000560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Snappers,Snappers,Regular,Family Lutjanidae.,NaN,NaN,0.950,0.0011,0.0013,1.750,8.984,...,0.000114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Pomfret (stromateids),Pomfret (stromateids),Regular,Family Stromateidae. Other pomfret-like famili...,NaN,0.2,0.950,0.2390,0.1080,3.030,15.150,...,0.016362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Adult hairtail (trichiurids),Adult hairtail (trichiurids),Regular,Trichiurus lepturus; definition: Family Trichi...,NaN,NaN,0.545,0.0072,0.0120,1.470,6.207,...,0.008026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Juvenile Hairtail (trichiurids),Juvenile Hairtail (trichiurids),Regular,Trichiurus lepturus; definition: Family Trichi...,NaN,NaN,0.749,0.0280,0.0150,3.080,14.894,...,0.011596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Lizard fish (synodontids),Lizard fish (synodontids),Regular,Saurida tumbil; S. undosquamis; definition: Fa...,NaN,NaN,0.658,0.0234,0.0320,1.600,5.407,...,0.017510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Bigeyes (priacanthids),Bigeyes (priacanthids),Regular,Family Priacanthidae.,NaN,NaN,0.550,0.2060,0.1300,3.330,11.300,...,0.194805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Threadfin bream (nemipterids),Threadfin bream (nemipterids),Regular,Nemipterus virgatus; N. bathybius; N. japonicu...,NaN,NaN,0.847,0.6570,0.2600,3.080,15.400,...,0.122522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Cephalopods,Cephalopods,Regular,Loligo edulis; L. chinensis; definition: Cepha...,NaN,NaN,0.393,0.2733,0.6800,3.100,8.000,...,1.279556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Crabs,Crabs,Regular,Crabs.,NaN,NaN,0.950,0.1997,0.3680,3.000,12.000,...,0.055200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Shrimps,Shrimps,Regular,Metapenaeopsis palmensis; M. barbata; definiti...,NaN,NaN,0.950,0.6788,0.1940,7.600,28.940,...,0.073720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Sessile/other invertebrates,Sessile/other invertebrates,Regular,"Sessile and other invertebrates, separate from...",NaN,NaN,0.575,0.0030,2.6100,1.000,9.000,...,1.109250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Non-ceph molluscs,Non-ceph molluscs,Regular,Non-cephalopod Mollusca.,NaN,NaN,0.951,0.7623,2.6800,3.500,11.700,...,0.459620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Benthic crustaceans,Benthic crustaceans,Regular,Benthic crustaceans excluding shrimps and crab...,NaN,NaN,0.617,0.0391,1.4300,5.650,26.900,...,3.094448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Echinoderms,Echinoderms,Regular,Echinodermata.,NaN,NaN,0.444,0.0021,1.9800,1.200,3.580,...,1.321056,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Polychaetes,Polychaetes,Regular,Polychaeta.,NaN,0.3,0.673,0.0000,2.2400,6.750,22.500,...,4.944240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Jellyfish,Jellyfish,Regular,Medusae of Cnidaria.,NaN,NaN,0.520,0.0440,1.5300,5.000,20.000,...,3.672000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Zooplankton,Zooplankton,Regular,Acetes spp.; definition: Zooplankton; explicit...,NaN,NaN,0.306,0.0948,9.0000,32.000,192.000,...,199.872000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Benthic producer,Benthic producer,PP,Benthic algae.,NaN,NaN,0.010,0.0056,153.0000,11.890,NaN,...,1800.978300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Phytoplankton,Phytoplankton,PP,"Phytoplankton dominated by diatoms, followed b...",NaN,NaN,0.010,0.0000,323.0000,398.000,NaN,...,127268.460000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
diet_import,diet_import,Import,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
calculator.get_groups_df().rename(index=model.seq2name, columns=model.seq2name).round(decimals=7)

,group_name,trophic_info,taxon_descr,tl,ge,ee,catch,biomass,pb,qb,...,gs,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import,det_export
group_seq,,,,,,,,,,,,,,,,,,,,,
diet_import,diet_import,Import,NaN,1.000000,0.000000,0.000,0.0000,1.0000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0
Detritus,Detritus,DET,Non-living detritus.,1.000000,1.000000,1.000,0.0000,100.0000,1296.890276,1296.890276,...,0.0,0.000000,0.000000,129061.412282,0.0,0.0,0.0,0.000000,0.0,0.0
Marine turtles,Marine turtles,Regular,Marine turtles; no species list documented.,2.972462,0.028571,0.300,0.0000,0.0002,0.100000,3.500000,...,0.2,0.000140,0.000540,0.000006,0.0,0.0,0.0,0.000154,0.0,0.0
Other mammals,Other mammals,Regular,Other marine mammals; no species list documented.,3.922805,0.010643,0.034,0.0000,0.0158,0.112000,10.523000,...,0.2,0.033253,0.131241,0.000060,0.0,0.0,0.0,0.034962,0.0,0.0
Pinnipeds,Pinnipeds,Regular,Pinnipeds; no species list documented.,4.146385,0.003047,0.290,0.0000,0.0046,0.045000,14.768000,...,0.2,0.013587,0.054139,0.000060,0.0,0.0,0.0,0.013733,0.0,0.0
Seabirds,Seabirds,Regular,Seabirds; no species list documented.,3.414701,0.000886,0.046,0.0000,0.0022,0.060000,67.759000,...,0.2,0.029814,0.119124,0.000006,0.0,0.0,0.0,0.029940,0.0,0.0
Pelagic sharks and rays,Pelagic sharks and rays,Regular,Pelagic elasmobranchs. No species list documen...,3.989709,0.200000,0.950,0.0007,0.0011,0.680000,3.400000,...,0.2,0.000748,0.002244,-0.000023,0.0,0.0,0.0,0.000785,0.0,0.0
Demersal sharks and rays,Demersal sharks and rays,Regular,Demersal elasmobranchs. No species list docume...,3.509427,0.200000,0.867,0.0010,0.0010,1.200000,6.000000,...,0.2,0.001200,0.003600,-0.000020,0.0,0.0,0.0,0.001360,0.0,0.0
Pelagic fish (> 30 cm),Pelagic fish (> 30 cm),Regular,"Pelagic fish with maximum total length >30 cm,...",3.367201,0.223285,0.759,0.0821,0.0790,1.400000,6.270000,...,0.2,0.099066,0.285664,-0.000070,0.0,0.0,0.0,0.125721,0.0,0.0
Juvenile large pelagic fish,Juvenile large pelagic fish,Regular,"Pelagic fish with maximum total length >30 cm,...",2.893397,0.264268,0.622,0.7384,0.2890,4.260000,16.120000,...,0.2,0.931736,2.495804,-0.028527,0.0,0.0,0.0,1.397107,0.0,0.0
Pelagic fish (≤ 30 cm),Pelagic fish (≤ 30 cm),Regular,Pelagic fish with maximum total length <=30 cm...,2.781667,0.250000,0.740,2.3450,1.7720,4.260000,17.040000,...,0.2,6.038976,16.607184,-0.009954,0.0,0.0,0.0,8.001643,0.0,0.0
Melon seed,Melon seed,Regular,Psenopsis anomala; definition: Psenopsis anomala.,3.034865,0.100417,0.994,0.0499,0.0700,2.410000,24.000000,...,0.2,0.336000,1.175300,-0.000034,0.0,0.0,0.0,0.337012,0.0,0.0
Benthopelagic fish,Benthopelagic fish,Regular,Final table has one Benthopelagic fish group. ...,2.780603,0.199741,0.479,0.6025,0.9220,3.080000,15.420000,...,0.2,2.843448,8.534032,-0.092350,0.0,0.0,0.0,4.322963,0.0,0.0
Adult demersal fish (> 30 cm),Adult demersal fish (> 30 cm),Regular,Demersal fish with maximum total length >30 cm...,3.427087,0.338328,0.747,0.0352,0.0210,2.100000,6.207000,...,0.2,0.026069,0.060178,-0.003729,0.0,0.0,0.0,0.037227,0.0,0.0
Juvenile demersal fish (> 30 cm),Juvenile demersal fish (> 30 cm),Regular,Demersal fish with maximum total length >30 cm...,3.043612,0.216799,0.722,0.3165,0.1430,3.500000,16.144000,...,0.2,0.461718,1.346374,-0.029299,0.0,0.0,0.0,0.600857,0.0,0.0
Demesral fish (≤ 30 cm),Demesral fish (≤ 30 cm),Regular,Demersal fish with maximum total length <=30 c...,3.009317,0.200000,0.950,0.1788,0.3160,4.700000,23.500000,...,0.2,1.485200,4.455600,-0.008043,0.0,0.0,0.0,1.559460,0.0,0.0
Croakers (> 30 cm),Croakers (> 30 cm),Regular,Larimichthys crocea; definition: Large Sciaeni...,3.472839,0.229461,0.587,0.0080,0.0094,1.430000,6.232000,...,0.2,0.011716,0.033423,-0.001042,0.0,0.0,0.0,0.017268,0.0,0.0
Juvenile large croakers,Juvenile large croakers,Regular,Larimichthys crocea; definition: Large Sciaeni...,3.238588,0.201637,0.564,0.0710,0.0400,3.300000,16.366000,...,0.2,0.130928,0.391712,-0.004749,0.0,0.0,0.0,0.188480,0.0,0.0
Croakers (≤ 30 cm),Croakers (≤ 30 cm),Regular,Agyrosomus spp.; Pennahia spp.; Pennahia (Agyr...,3.312753,0.292657,0.958,0.0351,0.0700,3.300000,11.276000,...,0.2,0.157864,0.400456,-0.002132,0.0,0.0,0.0,0.167566,0.0,0.0
Adult groupers,Adult groupers,Regular,Family Serranidae; the final table calls this ...,3.759047,0.286885,0.950,0.0089,0.0064,1.750000,6.100000,...,0.2,0.007808,0.020032,-0.000043,0.0,0.0,0.0,0.008368,0.0,0.0
Snappers,Snappers,Regular,Family Lutjanidae.,3.769209,0.194791,0.950,0.0011,0.0013,1.750000,8.984000,...,0.2,0.002336,0.007068,-0.000074,0.0,0.0,0.0,0.002450,0.0,0.0
Pomfret (stromateids),Pomfret (stromateids),Regular,Family Stromateidae. Other pomfret-like famili...,3.587017,0.200000,0.950,0.2390,0.1080,3.030000,15.150000,...,0.2,0.327240,0.981720,0.000040,0.0,0.0,0.0,0.343602,0.0,0.0
Adult hairtail (trichiurids),Adult hairtail (trichiurids),Regular,Trichiurus lepturus; definition: Family Trichi...,3.913682,0.236829,0.545,0.0072,0.0120,1.470000,6.207000,...,0.2,0.014897,0.041947,-0.000323,0.0,0.0,0.0,0.022923,0.0,0.0
Juvenile Hairtail (trichiurids),Juvenile Hairtail (trichiurids),Regular,Trichiurus lepturus; definition: Family Trichi...,3.878330,0.206795,0.749,0.0280,0.0150,3.080000,14.894000,...,0.2,0.044682,0.132528,-0.000172,0.0,0.0,0.0,0.056278,0.0,0.0
Lizard fish (synodontids),Lizard fish (synodontids),Regular,Saurida tumbil; S. undosquamis; definition: Fa...,3.856615,0.295913,0.658,0.0234,0.0320,1.600000,5.407000,...,0.2,0.034605,0.087219,-0.006244,0.0,0.0,0.0,0.052115,0.0,0.0
Bigeyes (priacanthids),Bigeyes (priacanthids),Regular,Family Priacanthidae.,3.471985,0.294690,0.550,0.2060,0.1300,3.330000,11.300000,...,0.2,0.293800,0.742300,0.005152,0.0,0.0,0.0,0.488605,0.0,0.0
Threadfin bream (nemipterids),Threadfin bream (nemipterids),Regular,Nemipterus virgatus; N. bathybius; N. japonicu...,3.210668,0.200000,0.847,0.6570,0.2600,3.080000,15.400000,...,0.2,0.800800,2.402400,-0.026599,0.0,0.0,0.0,0.923322,0.0,0.0
Cephalopods,Cephalopods,Regular,Loligo edulis; L. chinensis; definition: Cepha...,3.290814,0.387500,0.393,0.2733,0.6800,3.100000,8.000000,...,0.2,1.088000,2.244000,-0.001735,0.0,0.0,0.0,2.367556,0.0,0.0
Crabs,Crabs,Regular,Crabs.,2.523918,0.250000,0.950,0.1997,0.3680,3.000000,12.000000,...,0.2,0.883200,2.428800,-0.004478,0.0,0.0,0.0,0.938400,0.0,0.0
Shrimps,Shrimps,Regular,Metapenaeopsis palmensis; M. barbata; definiti...,2.314000,0.262612,0.950,0.6788,0.1940,7.600000,28.940000,...,0.2,1.122872,3.017088,-0.004182,0.0,0.0,0.0,1.196592,0.0,0.0
Sessile/other invertebrates,Sessile/other invertebrates,Regular,"Sessile and other invertebrates, separate from...",2.600000,0.111111,0.575,0.0030,2.6100,1.000000,9.000000,...,0.2,4.698000,16.182000,-0.000896,0.0,0.0,0.0,5.807250,0.0,0.0
Non-ceph molluscs,Non-ceph molluscs,Regular,Non-cephalopod Mollusca.,2.177778,0.299145,0.951,0.7623,2.6800,3.500000,11.700000,...,0.2,6.271200,15.704800,-0.002003,0.0,0.0,0.0,6.730820,0.0,0.0
Benthic crustaceans,Benthic crustaceans,Regular,Benthic crustaceans excluding shrimps and crab...,2.199822,0.210037,0.617,0.0391,1.4300,5.650000,26.900000,...,0.2,7.693400,22.694100,-0.014405,0.0,0.0,0.0,10.787849,0.0,0.0
Echinoderms,Echinoderms,Regular,Echinodermata.,2.333215,0.335195,0.444,0.0021,1.9800,1.200000,3.580000,...,0.2,1.417680,3.294720,-0.000158,0.0,0.0,0.0,2.738736,0.0,0.0
Polychaetes,Polychaetes,Regular,Polychaeta.,2.000000,0.300000,0.673,0.0000,2.2400,6.750000,22.500000,...,0.2,10.080000,25.200000,-0.004706,0.0,0.0,0.0,15.024240,0.0,0.0
Jellyfish,Jellyfish,Regular,Medusae of Cnidaria.,3.104071,0.250000,0.520,0.0440,1.5300,5.000000,20.000000,...,0.2,6.120000,16.830000,0.615572,0.0,0.0,0.0,9.792000,0.0,0.0
Zooplankton,Zooplankton,Regular,Acetes spp.; definition: Zooplankton; explicit...,2.000000,0.166667,0.306,0.0948,9.0000,32.000000,192.000000,...,0.2,345.600000,1094.400000,0.116163,0.0,0.0,0.0,545.472000,0.0,0.0
Benthic producer,Benthic producer,PP,Benthic algae.,1.000000,1.000000,0.010,0.0056,153.0000,11.890000,11.890000,...,0.0,0.000000,0.000000,-0.607228,0.0,0.0,0.0,1800.978300,0.0,0.0
Phytoplankton,Phytoplankton,PP,"Phytoplankton dominated by diatoms, followed b...",1.000000,1.000000,0.010,0.0000,323.0000,398.000000,398.000000,...,0.0,0.000000,0.000000,61.629039,0.0,0.0,0.0,127268.460000,0.0,0.0

# Is Model Balanced

In [ ]:
balanced, p, q = calculator.is_model_balanced()
balanced

True

In [ ]:
100 * (p - calculator.p)/p

group_seq
39             NaN
38    0.000000e+00
37    0.000000e+00
36    0.000000e+00
35    0.000000e+00
34    0.000000e+00
33    0.000000e+00
32    0.000000e+00
31    0.000000e+00
30    0.000000e+00
29    0.000000e+00
28    0.000000e+00
27    0.000000e+00
26    0.000000e+00
25    0.000000e+00
24    0.000000e+00
23    0.000000e+00
22    0.000000e+00
21    0.000000e+00
20    0.000000e+00
19    0.000000e+00
18    0.000000e+00
17    0.000000e+00
16   -1.501925e-14
15   -1.355253e-14
14    0.000000e+00
13    0.000000e+00
12    0.000000e+00
11    0.000000e+00
10    0.000000e+00
9     0.000000e+00
8     0.000000e+00
7     0.000000e+00
6     0.000000e+00
5     0.000000e+00
4     0.000000e+00
3     0.000000e+00
2     0.000000e+00
1     0.000000e+00
dtype: float64

In [ ]:
calc_balanced = calculator.balanced_model
print(calc_balanced.n_balance_runs)
balanced, p, q = calc_balanced.is_model_balanced()
100 * (p - calc_balanced.p)/p

1

group_seq
39             NaN
38    0.000000e+00
37    0.000000e+00
36    0.000000e+00
35    0.000000e+00
34    0.000000e+00
33    0.000000e+00
32    0.000000e+00
31    0.000000e+00
30    0.000000e+00
29    0.000000e+00
28    0.000000e+00
27    0.000000e+00
26    0.000000e+00
25    0.000000e+00
24    0.000000e+00
23    0.000000e+00
22    2.102695e-14
21    0.000000e+00
20   -1.548860e-14
19    0.000000e+00
18    0.000000e+00
17   -1.966807e-14
16    0.000000e+00
15   -1.355253e-14
14    1.282309e-14
13    0.000000e+00
12    0.000000e+00
11    2.011274e-14
10   -1.506000e-14
9     0.000000e+00
8     0.000000e+00
7     0.000000e+00
6     1.869062e-14
5     0.000000e+00
4     0.000000e+00
3     0.000000e+00
2     0.000000e+00
1     0.000000e+00
dtype: float64

# Diagnostics

In [ ]:
result, sppr, A, L = calc_balanced.diagnose_sppr(
    TE_option='GE',
    return_sppr=True
)

In [ ]:
result, sppr, A, L = calculator.diagnose_sppr(
    TE_option='TE',
    return_sppr=True
)

C:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\GlobalPPREstimation\tools\scientific_code\PPREstimation\PPRCalculator.py:2584: RuntimeWarning: 3 group(s) have near-zero TE (0 < EE << 1): 36 (Other mammals), 35 (Pinnipeds), 34 (Seabirds). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(

In [4]:
result, sppr, A, L = calculator.diagnose_sppr(
    TE_option='GE',
    return_sppr=True
)

In [6]:
result['model_input']

{'status': 'OK',
 'is_model_balanced': True,
 'p_max_rel_residual': 1.501925087425807e-16,
 'q_max_rel_residual': 2.1293605234971967e-16,
 'dc_rows_sum_to_1': True,
 'dc_max_deviation': 2.220446049250313e-16,
 'n_negative_catch': 0,
 'n_zero_catch': 8,
 'total_catch': 7.737500000000001,
 'has_catch': True,
 'has_ee_issues': False,
 'n_ee0': 0,
 'n_ee_marginal': 0,
 'n_ee_gt_1': 0,
 'ee0_groups': [],
 'ee_marginal_groups': []}

In [5]:
result['divergence']

{'status': 'WARN',
 'solve_error': None,
 'b': 0.0040813821236433895,
 'b_converges': True,
 'rho_living': 0.32091875376096113,
 'living_converges': True,
 'sppr_det': {38: 1.0077829362166681},
 'max_sppr_det': 1.0077829362166681,
 'max_sppr_group': {'seq': 34,
  'tl': 3.4001860292997397,
  'sppr': 21226.417530598454,
  'inv_te': 1129.3166666666666},
 'max_tl_group': {'seq': 35,
  'tl': 4.112805367463004,
  'sppr': 12910.880433533632,
  'inv_te': 328.1777777777778},
 'n_negative_sources': 0,
 'expect_negatives': False,
 'near_singular_te': [34]}

In [ ]:
result['balance']

{'status': 'OK',
 'is_balanced': True,
 'inflow': 130373.17,
 'outflow': 130373.17000000001,
 'rel_gap': 1.1161740738809106e-16}

In [7]:
result['footprint']

{'ppr_all': 231.55157149794962,
 'ppr_inner': 231.55157149794962,
 'ppr_pp_only': 136.04732188913857,
 'npp': 130373.17,
 'ppr2npp': 0.0017760676640596346,
 'ppr2npp_pp_only': 0.001043522389531056}

In [8]:
result['config']

{'TE_option': 'GE',
 'det_open_mode': 'none',
 'det_theta': 1.0,
 'det_external_sppr': 0.0,
 'det_collapse_mode': 'never',
 'explicit_TE': False,
 'method': 'single_detritus',
 'would_pool': False,
 'model': 'Northern South China Sea (2000s)'}

In [9]:
result['warnings']

['1 group(s) have near-zero TE (SPPR ~ 1/te is near-singular): [34]']